### PR TITLE
Give housekeeping struct packed attribute

### PR DESCRIPTION
**Pull request by wagnerd97**

### CODE REVIEW

**Comment by ArashYzd** [comment]
Why aren't you using [HAL_S_getHK](https://github.com/AlbertaSat/ex2_sband_software/blob/master/hardware_interface/include/sband.h#L93)? It has its own packed struct [Sband_Housekeeping](https://github.com/AlbertaSat/ex2_sband_software/blob/master/hardware_interface/include/sband.h#L93). And, I believe we don't want to call equipment handler functions directly from higher levels. That's why we have HAL.

**Comment by wagnerd97** [comment]
> Why aren't you using [HAL_S_getHK](https://github.com/AlbertaSat/ex2_sband_software/blob/master/hardware_interface/include/sband.h#L93)? It has its own packed struct [Sband_Housekeeping](https://github.com/AlbertaSat/ex2_sband_software/blob/master/hardware_interface/include/sband.h#L93). And, I believe we don't want to call equipment handler functions directly from higher levels. That's why we have HAL.

Because I didn't know that existed lol

**Comment by ArashYzd** [comment]
It's actually our fault. Your work is highly dependant on others' codes and there's no written guideline for the HK task.
Btw, If you're wondering about ADCS, the HAL functions are yet to be developed, so maybe use a mocked HAL_adcs_getHK and leave a TODO comment, so we can update that later.

**Comment by wagnerd97** [comment]
That's alright. luckily I made it easy to change. So now it calls the appropriate sBand function and has placeholders of format
//TODO:
//code
in all the spots where ADCS stuff needs to go. so when it's made it'll be mostly as simple as uncommenting each line of code and deleting the TODO heading

**Pull request closed without merging**
